# GitHub Sponsors button configuration
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
#
# Maintained directly in this GitHub repository.

github: [InventoCasa]
buy_me_a_coffee: henrikic
